# Generated by Django 5.2.6 on 2025-09-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0002_tag_alter_post_options_post_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="tags",
        ),
    ]
