# Generated by Django 5.2.6 on 2025-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0003_rename_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="artist",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
