# Generated by Django 5.2.6 on 2025-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0004_post_artist_post_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="artist",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
