# Generated by Django 5.2.6 on 2025-11-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "a_posts",
            "0005_alter_post_artist_alter_post_image_alter_post_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("GIVE", "I want to GIVE"), ("REQUEST", "I need to REQUEST")],
                default="GIVE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Why are you giving this away? or Why do you need this item/skill?",
            ),
        ),
    ]
