# Generated by Django 5.2.6 on 2025-11-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0006_post_post_type_post_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="post",
            name="show_general_area_only",
            field=models.BooleanField(default=False),
        ),
    ]
