# Generated by Django 5.2.6 on 2025-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0007_post_latitude_post_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="display_area",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
