# Generated by Django 5.2.6 on 2025-11-12 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_post_display_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True, default='', help_text='User self-introduction', max_length=500)),
                ('reputation_score', models.FloatField(default=5.0, help_text='Average rating from transactions (e.g., 4.9)')),
                ('total_contributions', models.IntegerField(default=0, help_text='Count of successfully completed Give posts and Skill Offers')),
                ('success_rate', models.FloatField(default=100.0, help_text='Percentage of follow-through on transactions')),
                ('location_display', models.CharField(blank=True, default='', help_text='General area where user shares (e.g., Osaka-shi, Kita-ku)', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='ID verification status')),
                ('followers_count', models.IntegerField(default=0, help_text='Number of followers/neighbors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
