# Generated by Django 5.2.6 on 2025-11-12 04:36

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('a_posts', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0009_post_user_userprofile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, reverse_migration),
    ]
