# Generated by Django 5.2.6 on 2026-01-15 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0012_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('follow', 'New Follower'), ('review', 'New Review'), ('post', 'New Post'), ('system', 'System Message')], default='system', max_length=20)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', help_text='URL to redirect when notification is clicked', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who receives the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered the notification (null for system messages)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
