# Generated by Django 5.2.6 on 2026-01-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0015_add_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
