# Generated by Django 5.2.6 on 2026-01-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0016_make_post_image_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant1', models.ForeignKey(help_text='Post owner', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_p1', to=settings.AUTH_USER_MODEL)),
                ('participant2', models.ForeignKey(help_text='User who initiated the chat', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_p2', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The post this conversation is about', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='a_posts.post')),
            ],
            options={
                'verbose_name': 'チャットルーム',
                'verbose_name_plural': 'チャットルーム一覧',
                'ordering': ['-updated_at'],
                'unique_together': {('post', 'participant1', 'participant2')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a_posts.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ一覧',
                'ordering': ['created_at'],
            },
        ),
    ]
