# Generated by Django 5.2.6 on 2026-01-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0017_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acceptable_condition',
            field=models.CharField(blank=True, default='', help_text='Acceptable condition for REQUEST posts (any, good, like_new)', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Specific deadline date for REQUEST posts', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='urgency',
            field=models.CharField(blank=True, choices=[('asap', 'できるだけ早く'), ('week', '1週間以内'), ('no_rush', '急ぎではない'), ('custom', '日付を指定')], default='', help_text='Urgency level for REQUEST posts', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('review', 'New Review'), ('post', 'New Post'), ('message', 'New Message'), ('system', 'System Message')], default='system', max_length=20),
        ),
    ]
